### ISSUE TITLE
Is it posssible to set  a preferred line separator?

### ISSUE THREAD

**Issue by axkr** [freva/ascii-table#16]
Can we have an option to set a preferred line separator instead of `System.lineSeparator()`?

https://github.com/freva/ascii-table/blob/202d95bed326de8f658252188301281929039fbd/src/main/java/com/github/freva/asciitable/AsciiTable.java#L99

**Comment by freva** [comment]
Sounds reasonable, but I think I'll have to refactor a bit and create a builder, otherwise there's gonna be too many public methods to cover all the permutations of possible arguments. I'll be a bit busy in coming days, but I'll try to take a look at this before September.

**Comment by freva** [comment]
Added in 1.6.0, see https://github.com/freva/ascii-table/blob/e5b29cd0698dc3bf203c470bca2888d4dfbb2401/README.md#builder for example.
