### ISSUE TITLE
Cut column in start instead of end

### ISSUE THREAD

**Issue by davsclaus** [freva/ascii-table#17]
I would like to be able to cut the column value in the start, so the visible text is the suffix text, eg

I have this class name `sample.camel.MyCamelApplication` which are shown in full in the PS command below
```
~/workspace ❯ camel ps
  PID   NAME                             AGE
 61818  sample.camel.MyCamelApplication   5s
```

However in the next command with more details I want to cut the class name in the beginning, eg:

```
~/workspace ❯ camel get
  PID   NAME                          CAMEL            PLATFORM            READY   STATE   AGE  TOTAL  FAILED  INFLIGHT  SINCE-LAST
 61818  sample.camel.MyCamelApplica…  3.19.0-SNAPSHOT  Spring Boot v2.7.3   1/1   Started   9s      3       0         0          0s

Should be `....camel.MyCamelApplication`
```

PS: Thanks for implementing the other features so quickly, we use this table library with joy at Apache Camel for our new CLI.

**Comment by davsclaus** [comment]
This is the column for NAME
```
                    new Column().header("NAME").dataAlign(HorizontalAlign.LEFT).maxWidth(30, OverflowBehaviour.ELLIPSIS)
                            .with(r -> r.name),
```

So if we have another overflow ala

```
                    new Column().header("NAME").dataAlign(HorizontalAlign.LEFT).maxWidth(30, OverflowBehaviour.LEFT_ELLIPSIS)
                            .with(r -> r.name),
```

I dont know what a great name would be I just typed LEFT_ELLIPSIS.

**Comment by freva** [comment]
Great, glad you find this useful!

Added `ELLIPSIS_LEFT` and `CUT_LEFT` in 1.5.0.
