### ISSUE TITLE
Hyperlinks aren't rendered correclty

### ISSUE THREAD

**Issue by svartkanin** [freva/ascii-table#25]
I'm using this extension to produce output that is a hyperlink https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda. 
When using a hyperlink as a value then the width of it isn't calculated correctly. 
As an example consider the following value 
```
\u001B]8;;http://example.com\u001B\\This is a link\u001B]8;;\u001B\\\n
```
I'd expect the value to be displayed in the column to be only `This is a link` but I think it's calculating the width on all characters

**Comment by freva** [comment]
Yes, the table will be misaligned if it gets any zero-width characters in the data. The solution is to only pass visible characters to let the library size up everything correctly, then use the [Styler](https://github.com/freva/ascii-table/blob/master/src/main/java/com/github/freva/asciitable/Styler.java) interface to add your link. See https://github.com/freva/ascii-table/blob/aa82c99750ca0358fe261ffab6e14274f3b968e8/src/test/java/com/github/freva/asciitable/AsciiTableTest.java#L607:L649 for an example.

**Comment by svartkanin** [comment]
That's exactly what I needed, thanks!
