### ISSUE TITLE
Ansi color glitch in adjacent cell

### ISSUE THREAD

**Issue by davsclaus** [freva/ascii-table#26]
Hi

Many thanks for this great table printer.

Just in case you want to see what we have been up to of late with Apache Camel, then we have a panel in the middle with 2 columns. When using ansi color then the 2nd panel will start out of position.

I think you have been aware of this and its tricky to solve. But just wanted to show you a real world use of this great util.

<img width="2135" alt="Screenshot 2023-11-03 at 13 11 28" src="https://github.com/freva/ascii-table/assets/477100/cab7c9f2-0fbc-40e4-9d4d-e0f3a986a285">

**Comment by davsclaus** [comment]
Ah sorry I remember you added Styler in #23 - let me try that, thanks

**Comment by davsclaus** [comment]
Okay first try I cannot get styler to work properly either

<img width="2091" alt="Screenshot 2023-11-03 at 13 31 45" src="https://github.com/freva/ascii-table/assets/477100/cacfba03-cd78-4985-b0b2-281f2058378a">

**Comment by davsclaus** [comment]
I made my own hacky table but the solution for me, was to specify the cell length - so I could dictate the length from the raw string (no ansi codes), and this allows me to render the cells correctly.

I am not sure if there is a way to make Style know a length for each cell / data.

**Comment by freva** [comment]
Thanks for the update, looks great!

Could you create a minimal test case that reproduces the issue?

**Comment by davsclaus** [comment]
Yes I will try to get this done later - I am a bit busy but ping me in a few weeks if I haven't provide a test case

**Comment by freva** [comment]
@davsclaus ping :)

**Comment by davsclaus** [comment]
sorry I wont find time for this, and my use-case is a special-case so lets just close this ticket
