### ISSUE TITLE
using AsciiTable as email body

### ISSUE THREAD

**Issue by ondiekisteven** [freva/ascii-table#6]
Hi, I hope it's ok to ask this here. I am using AsciiTable to create an email body and it seems to work fine on thunderbird, but its a bit broken on windows outlook.

i get this nice table in thunderbird:
![image](https://user-images.githubusercontent.com/24654537/179745002-c01a0fc9-2fc9-4715-ba48-34d980367b86.png)

this is what it displays on outlook

![image](https://user-images.githubusercontent.com/24654537/179744874-d0d57470-f781-44a6-9bde-200bc582e3c4.png)

does anyone know anything i can do to get this working on outlook better? or any suggestions will be appreciated

**Comment by freva** [comment]
This only works with a monospaced font. One way would be to wrap the table with some HTML, e.g. `<div style="white-space:pre-wrap;font-family:monospace">`. See https://codepen.io/freva/pen/oNqZyPE?editors=1000 for an example. Note that the first table does not use monospaced font, so you get a result similar to what you are getting in outlook, while the second one is perfectly aligned.

**Comment by ondiekisteven** [comment]
Thanks for this. Ive tried but it seems to have no effect. From some searches online, I've discovered that you cant control which font outlook will use to display emails on client side.
