### ISSUE TITLE
Couldn't create a table from Collections

### ISSUE THREAD

**Issue by sibiarunachalam** [freva/ascii-table#7]
Hi 
Couldn't create a table from Collection, because the ColumnData constructor is package private.
So I could use that constructor from AsciiTable.

**Comment by freva** [comment]
See https://github.com/freva/ascii-table#table-from-collections for how to create table from Collection. The `Column::with` method returns `ColumnData`.

**Comment by sibiarunachalam** [comment]
Thanks @freva  for your feedback, it works.
